// src/Pages/Search.svelte
<script>
  import crawlerAPI from "../api/api";
  let medias = [];
  let searchQuery = "";
  let type = "anime";
  const search = async (type = "anime") => {
    switch (type) {
      case "anime":
        crawlerAPI.fetchAnime({ search: searchQuery }).then((res) => {
          medias = res.map((item) => {
            return {
              title: item.title,
              // Only grab the /anime/ part of the url
              link: `/#/anime/${item.link}`,
            };
          });
        });
        break;
      case "movie":
        crawlerAPI.searchFlick({ search: searchQuery }).then((res) => {
          medias = res.map((item) => {
            return {
              title: item.title,
              // Only grab the /movie/ part of the url
              link: `/#${item.link}`,
            };
          });
        });
        break;
      case "tv":
        crawlerAPI.SearchSeries({ search: searchQuery }).then((res) => {
          medias = res.map((item) => {
            return {
              title: item.title,
              // Only grab the /movie/ part of the url
              link: `/#${item.link}`,
            };
          });
        });
        break;
    }
  };
</script>

<div class="inner">
  <div style="padding-top: 0.5em; padding-left: 1em;" class="center">
    <center>
      <h4>Fucking Media Sideloader Bullshit</h4>
    </center>
    <div class="form-group">
      <input
        type="text"
        bind:value={searchQuery}
        placeholder="Search"
        style="width: 50%;"
      />

      <button
        on:click={() => {
          search(type);
        }}
        class="btn btn-default"
      >
        Search
      </button>
    </div>
    <div class="form-group">
      <label for="select">Select Media Type:</label>
      <select
        id="select"
        name="select"
        bind:value={type}
        style="padding: 0.8em; background-color: black; color: white; font-family: inherit"
      >
        <option value="anime"> Anime </option>
        <option value="movie"> Movie </option>
        <option value="tv"> TV Series </option>
      </select>
    </div>
  </div>
  <ul>
    {#each medias as media}
      <li>
        > <a href={`${media.link}`}>
          <!-- <img src={anime.image} alt={anime.title} width="32" height="32"/> -->
          <span>{media.title}</span>
        </a>
      </li>
    {/each}
  </ul>
</div>

// src/Pages/Search.jsx
import { useEffect, useState } from "preact/hooks";
import routes from "../api/APIRoutes";

export default function Search() {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("anime");
  const [result, setResult] = useState([]);
  const handleSearch = async () => {
    switch (type) {
      case "anime":
        await routes.fetchAnime(query).then((r) => setResult(r));
        break;
      case "tv":
        await routes.fetchSeries(query).then((r) => setResult(r));
        break;
      case "movie":
        await routes.fetchMovie(query).then((r) => setResult(r));
        break;
    }
  };

  useEffect(() => {
    console.log(type);
  }, [type])

  useEffect(() => {
    console.log(result);
  }, [result]);

  return (
    <div class="inner">
      <div style="padding-top: 0.5em; padding-left: 1em;" class="center">
        <center>
          <h4>Fucking Media Sideloader Bullshit</h4>
        </center>
        <div class="form-group">
          <input
            type="text"
            onInput={(e) => {
              setQuery(e.target.value);
            }}
            placeholder="Search"
            value={query}
            style="width: 50%;"
          />

          <div class="form-group">
            <label for="select">Select field:</label>
            <select onChange={(e) => {
              setType(e.target.value);
            }} id="select" name="select">
              <option value={"anime"}> Anime </option>
              <option value={"tv"}> TV Series</option>
              <option value={"movie"}> Movie </option>
            </select>
          </div>

          <button class="btn btn-default" onClick={handleSearch}>
            Search
          </button>
        </div>
      </div>
      <ul>
        {result.map((item) => {
          return (
            <li>
              <a href={`${window.origin}/${item.id}`}>
                <span>{item.title}</span>
              </a>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
